version: '3'

services:
  app:
    build: backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  ui:
    build: ui
    ports:
      - "4200:80"

  redis:
    image: redis
    ports:
      - "6379:6379"