version: '3'
services:
  app:
    build: backend/Dockerfile
    ports:
      - "8080:8080"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - cache
    env_file:
      - .env

  ui:
    build: ui
    ports:
      - "4200:80"
    depends_on:
      - app

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - cache
    command: redis-server --appendonly yes --replica-read-only no

networks:
  cache:
