version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - cache
    env_file:
      - .env

  ui:
    build: ui
    ports:
      - "4200:80"
    depends_on:
      - app
    links:
      - app

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - cache

networks:
  cache: